/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorSettingsRouteImport } from './routes/calculator-settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as EnquiriesViewRouteImport } from './routes/enquiries.$view'
import { Route as EnquiriesViewIndexRouteImport } from './routes/enquiries.$view.index'
import { Route as EnquiriesViewIdRouteImport } from './routes/enquiries.$view.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorSettingsRoute = CalculatorSettingsRouteImport.update({
  id: '/calculator-settings',
  path: '/calculator-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiriesViewRoute = EnquiriesViewRouteImport.update({
  id: '/enquiries/$view',
  path: '/enquiries/$view',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiriesViewIndexRoute = EnquiriesViewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnquiriesViewRoute,
} as any)
const EnquiriesViewIdRoute = EnquiriesViewIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EnquiriesViewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator-settings': typeof CalculatorSettingsRoute
  '/projects': typeof ProjectsRoute
  '/enquiries/$view': typeof EnquiriesViewRouteWithChildren
  '/enquiries/$view/$id': typeof EnquiriesViewIdRoute
  '/enquiries/$view/': typeof EnquiriesViewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator-settings': typeof CalculatorSettingsRoute
  '/projects': typeof ProjectsRoute
  '/enquiries/$view/$id': typeof EnquiriesViewIdRoute
  '/enquiries/$view': typeof EnquiriesViewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator-settings': typeof CalculatorSettingsRoute
  '/projects': typeof ProjectsRoute
  '/enquiries/$view': typeof EnquiriesViewRouteWithChildren
  '/enquiries/$view/$id': typeof EnquiriesViewIdRoute
  '/enquiries/$view/': typeof EnquiriesViewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator-settings'
    | '/projects'
    | '/enquiries/$view'
    | '/enquiries/$view/$id'
    | '/enquiries/$view/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator-settings'
    | '/projects'
    | '/enquiries/$view/$id'
    | '/enquiries/$view'
  id:
    | '__root__'
    | '/'
    | '/calculator-settings'
    | '/projects'
    | '/enquiries/$view'
    | '/enquiries/$view/$id'
    | '/enquiries/$view/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorSettingsRoute: typeof CalculatorSettingsRoute
  ProjectsRoute: typeof ProjectsRoute
  EnquiriesViewRoute: typeof EnquiriesViewRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator-settings': {
      id: '/calculator-settings'
      path: '/calculator-settings'
      fullPath: '/calculator-settings'
      preLoaderRoute: typeof CalculatorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiries/$view': {
      id: '/enquiries/$view'
      path: '/enquiries/$view'
      fullPath: '/enquiries/$view'
      preLoaderRoute: typeof EnquiriesViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiries/$view/': {
      id: '/enquiries/$view/'
      path: '/'
      fullPath: '/enquiries/$view/'
      preLoaderRoute: typeof EnquiriesViewIndexRouteImport
      parentRoute: typeof EnquiriesViewRoute
    }
    '/enquiries/$view/$id': {
      id: '/enquiries/$view/$id'
      path: '/$id'
      fullPath: '/enquiries/$view/$id'
      preLoaderRoute: typeof EnquiriesViewIdRouteImport
      parentRoute: typeof EnquiriesViewRoute
    }
  }
}

interface EnquiriesViewRouteChildren {
  EnquiriesViewIdRoute: typeof EnquiriesViewIdRoute
  EnquiriesViewIndexRoute: typeof EnquiriesViewIndexRoute
}

const EnquiriesViewRouteChildren: EnquiriesViewRouteChildren = {
  EnquiriesViewIdRoute: EnquiriesViewIdRoute,
  EnquiriesViewIndexRoute: EnquiriesViewIndexRoute,
}

const EnquiriesViewRouteWithChildren = EnquiriesViewRoute._addFileChildren(
  EnquiriesViewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorSettingsRoute: CalculatorSettingsRoute,
  ProjectsRoute: ProjectsRoute,
  EnquiriesViewRoute: EnquiriesViewRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
